class I1 {
                      

     void pro(float a) {

         
     }

      void pro(int x) {

         
      }

       void pro(byte b) {

         
       }

        void pro (short y) {

             
        }

         void pro(int x) {

             
         }

}

        //  I1.java:25: error: method pro(int) is already defined in class I1
        //  void pro(int x) {
        //       ^
         //1 error
